#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AGENTS_BIN="$HOME/.agents/bin"
TARGET="$AGENTS_BIN/codex"

usage() {
  cat <<EOF
Usage: codex-shim-install.sh [install|remove|status]

Installs an optional legacy agmsg Codex bridge shim at:
  $TARGET

Put ~/.agents/bin before the real Codex binary on PATH only for legacy bridge
compatibility. The shim routes interactive Codex launches through the old
app-server bridge only when AGMSG_CODEX_BRIDGE=1 is set and the current project
is in Codex monitor mode.
EOF
}

is_agmsg_shim() {
  [ -f "$TARGET" ] && grep -Eq "Optional Codex entrypoint shim for agmsg (monitor mode|legacy bridge)" "$TARGET" 2>/dev/null
}

shell_quote() {
  printf '%q' "$1"
}

cmd="${1:-install}"
case "$cmd" in
  -h|--help)
    usage
    ;;
  install)
    mkdir -p "$AGENTS_BIN"
    if [ -e "$TARGET" ] && ! is_agmsg_shim; then
      echo "codex-shim-install: refusing to overwrite existing $TARGET" >&2
      echo "codex-shim-install: move it aside or remove it first" >&2
      exit 1
    fi
    {
      echo "#!/usr/bin/env bash"
      echo "set -euo pipefail"
      echo ""
      echo "# Optional Codex entrypoint shim for agmsg legacy bridge."
      echo "# Generated by agmsg. Dispatches to the installed skill script."
      echo ""
      echo "export AGMSG_CODEX_SHIM_WRAPPER=1"
      echo "export AGMSG_CODEX_SHIM_SCRIPT_DIR=$(shell_quote "$SCRIPT_DIR")"
      echo "export AGMSG_CODEX_SHIM_TARGET=$(shell_quote "$TARGET")"
      echo "exec $(shell_quote "$SCRIPT_DIR/codex-shim.sh") \"\$@\""
    } > "$TARGET"
    chmod +x "$TARGET"
    if [ "${AGMSG_CODEX_SHIM_INSTALL_QUIET:-}" != "1" ]; then
      echo "installed: $TARGET"
      case ":$PATH:" in
        *":$AGENTS_BIN:"*) ;;
        *)
          echo "note: add $AGENTS_BIN before the real Codex binary on PATH"
          ;;
      esac
    fi
    ;;
  remove|uninstall)
    if is_agmsg_shim; then
      rm -f "$TARGET"
      echo "removed: $TARGET"
    elif [ -e "$TARGET" ]; then
      echo "codex-shim-install: $TARGET exists but is not the agmsg shim; leaving it untouched" >&2
      exit 1
    else
      echo "not installed: $TARGET"
    fi
    ;;
  status)
    if is_agmsg_shim; then
      echo "installed: $TARGET"
    else
      echo "not installed: $TARGET"
    fi
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
