#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AGENTS_BIN="$HOME/.agents/bin"
TARGET="$AGENTS_BIN/codex"

usage() {
  cat <<EOF
Usage: codex-shim-install.sh [function|install|remove|status]

Prints a backwards-compatible Codex shell function.
With no subcommand, prints the function.

The optional global PATH shim can still be installed at:
  $TARGET

Native Codex monitor mode no longer needs a launch shim. The generated function
and PATH shim pass through to the real Codex binary, preserving older shell
profiles while avoiding the legacy app-server bridge.
EOF
}

is_agmsg_shim() {
  [ -f "$TARGET" ] && grep -q "Optional Codex entrypoint shim for agmsg monitor mode" "$TARGET" 2>/dev/null
}

shell_quote() {
  printf '%q' "$1"
}

cmd="${1:-function}"
case "$cmd" in
  -h|--help)
    usage
    ;;
  function|print-function|shell-function)
    cat <<EOF
# agmsg Codex compatibility shim. Native monitor mode does not require it.
codex() {
  bash $(shell_quote "$SCRIPT_DIR/codex-shim.sh") "\$@"
}
EOF
    ;;
  install)
    mkdir -p "$AGENTS_BIN"
    if [ -e "$TARGET" ] && ! is_agmsg_shim; then
      echo "codex-shim-install: refusing to overwrite existing $TARGET" >&2
      echo "codex-shim-install: move it aside or remove it first" >&2
      exit 1
    fi
    {
      echo "#!/usr/bin/env bash"
      echo "set -euo pipefail"
      echo ""
      echo "# Optional Codex entrypoint shim for agmsg monitor mode."
      echo "# Generated by agmsg. Dispatches to the installed skill script."
      echo ""
      echo "export AGMSG_CODEX_SHIM_WRAPPER=1"
      echo "export AGMSG_CODEX_SHIM_SCRIPT_DIR=$(shell_quote "$SCRIPT_DIR")"
      echo "export AGMSG_CODEX_SHIM_TARGET=$(shell_quote "$TARGET")"
      echo "exec bash $(shell_quote "$SCRIPT_DIR/codex-shim.sh") \"\$@\""
    } > "$TARGET"
    chmod +x "$TARGET"
    if [ "${AGMSG_CODEX_SHIM_INSTALL_QUIET:-}" != "1" ]; then
      echo "installed: $TARGET"
      case ":$PATH:" in
        *":$AGENTS_BIN:"*) ;;
        *)
          echo "note: this optional global shim needs $AGENTS_BIN before the real Codex binary on PATH"
          ;;
      esac
    fi
    ;;
  remove|uninstall)
    if is_agmsg_shim; then
      rm -f "$TARGET"
      echo "removed: $TARGET"
    elif [ -e "$TARGET" ]; then
      echo "codex-shim-install: $TARGET exists but is not the agmsg shim; leaving it untouched" >&2
      exit 1
    else
      echo "not installed: $TARGET"
    fi
    ;;
  status)
    if is_agmsg_shim; then
      echo "installed: $TARGET"
    else
      echo "not installed: $TARGET"
    fi
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
